services:
  buzzdrop:
    build: .
    container_name: buzzdrop_app
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./buzzdrop.db:/app/buzzdrop.db
    env_file:
      - .env
    restart: unless-stopped
